USE visualmodasbykel;

INSERT INTO produtos (
    nome,
    descricao,
    preco,
    tamanho,
    categoria,
    secao,
    genero,
    foto_url,
    usuario_id,
    ativo
) VALUES
    (
        'Calça Alfaiataria Areia',
        'Calça bege com modelagem reta.',
        219.90,
        'M',
        'Calças',
        'Novidades',
        'Feminino',
        '/uploads/produtos/198-OK.jpg',
        1,
        1
    ),
    (
        'Calça Flare Chocolate',
        'Calça marrom escura estilo flare.',
        239.90,
        'M',
        'Calças',
        'Novidades',
        'Feminino',
        '/uploads/produtos/314-OK.jpg',
        1,
        1
    ),
    (
        'Calça Jeans Capri Azul',
        'Calça jeans azul capri.',
        199.90,
        'P',
        'Calças',
        'Novidades',
        'Feminino',
        '/uploads/produtos/647-OK.jpg',
        1,
        1
    ),
    (
        'Shorts Laço Pistache',
        'Shorts verde claro de cintura alta.',
        159.90,
        'P',
        'Shorts e Bermudas',
        'Novidades',
        'Feminino',
        '/uploads/produtos/822-OK.jpg',
        1,
        1
    ),
    (
        'Shorts Laço Dourado',
        'Shorts amarelo claro de cintura alta.',
        159.90,
        'P',
        'Shorts e Bermudas',
        'Novidades',
        'Feminino',
        '/uploads/produtos/780-OK.jpg',
        1,
        1
    ),
    (
        'Calça Pantalona Marinho',
        'Calça pantalona azul marinho cintura alta.',
        249.90,
        'G',
        'Calças',
        'Novidades',
        'Feminino',
        '/uploads/produtos/468-OK.jpg',
        1,
        1
    ),
    (
        'Macacão Areia Casual',
        'Macacão bege manga longa casual.',
        289.90,
        'M',
        'Macacões',
        'Novidades',
        'Feminino',
        '/uploads/produtos/326-OK.jpg',
        1,
        1
    ),
    (
        'Macacão Utilitário Duna',
        'Macacão bege utilitário com bolsos.',
        299.90,
        'M',
        'Macacões',
        'Destaques',
        'Feminino',
        '/uploads/produtos/980-OK.jpg',
        1,
        1
    ),
    (
        'Vestido Midi Mostarda',
        'Vestido midi mostarda com gola.',
        269.90,
        'M',
        'Vestidos',
        'Destaques',
        'Feminino',
        '/uploads/produtos/962-OK.jpg',
        1,
        1
    ),
    (
        'Vestido Jeans Botões',
        'Vestido jeans curto com botões.',
        229.90,
        'P',
        'Vestidos',
        'Destaques',
        'Feminino',
        '/uploads/produtos/872-OK.jpg',
        1,
        1
    ),
    (
        'Calça Jeans Skinny Ice',
        'Calça jeans skinny azul clara.',
        209.90,
        'M',
        'Calças',
        'Destaques',
        'Feminino',
        '/uploads/produtos/492-OK.jpg',
        1,
        1
    ),
    (
        'Saia Longa Terracota',
        'Saia longa terracota cintura alta.',
        189.90,
        'M',
        'Saias',
        'Destaques',
        'Feminino',
        '/uploads/produtos/370-OK.jpg',
        1,
        1
    ),
    (
        'Saia Midi Bege Savana',
        'Saia midi bege corte reto.',
        179.90,
        'P',
        'Saias',
        'Destaques',
        'Feminino',
        '/uploads/produtos/366-OK.jpg',
        1,
        1
    ),
    (
        'Vestido Preto Evasê Noite',
        'Vestido preto evasê mangas curtas.',
        259.90,
        'M',
        'Vestidos',
        'Destaques',
        'Feminino',
        '/uploads/produtos/280-OK.jpg',
        1,
        1
    ),
    (
        'Vestido Longo Preto Gala',
        'Vestido longo preto alças finas.',
        299.90,
        'M',
        'Vestidos',
        'Destaques',
        'Feminino',
        '/uploads/produtos/233-OK.jpg',
        1,
        1
    ),
    (
        'Shorts Bege Terracota',
        'Shorts bege claro look casual.',
        149.90,
        'M',
        'Shorts e Bermudas',
        'Geral',
        'Feminino',
        '/uploads/produtos/687-OK.jpg',
        1,
        1
    ),
    (
        'Shorts Bege High Waist',
        'Shorts bege de cintura alta.',
        149.90,
        'P',
        'Shorts e Bermudas',
        'Geral',
        'Feminino',
        '/uploads/produtos/795-OK.jpg',
        1,
        1
    ),
    (
        'Bermuda Bege Reta',
        'Bermuda bege de corte reto.',
        139.90,
        'M',
        'Shorts e Bermudas',
        'Geral',
        'Feminino',
        '/uploads/produtos/388-OK.jpg',
        1,
        1
    ),
    (
        'Blusa Tricot Off',
        'Blusa branca de tricot manga longa.',
        169.90,
        'M',
        'Blusas e Camisas',
        'Geral',
        'Feminino',
        '/uploads/produtos/251-OK.jpg',
        1,
        1
    ),
    (
        'Calça Alfaiataria Siena',
        'Calça bege de alfaiataria reta.',
        219.90,
        'G',
        'Calças',
        'Geral',
        'Feminino',
        '/uploads/produtos/167-OK.jpg',
        1,
        1
    );
